# Auto-populated Variables (set by Cloud Build)
# $PROJECT_ID
# $COMMIT_SHA
#
# Template Variables (set in trigger)
# $_IMAGE_NAME
# $_SSH_STRING
# $_ZONE
# $_HOME

steps:
# Update submodules
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git submodule init
    git submodule update
# build hugo site
# See ./hugo-builder/README.md
- name: 'sidpalas/cloud-builder-hugo:0.64.1'
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA']
# cleanup existing containers
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - '$_SSH_STRING'
  - '--project'
  - '$PROJECT_ID'
  - '--zone'
  - '$_ZONE'
  - '--'
  - 'docker container stop $$(docker container ls -aq) && docker container rm $$(docker container ls -aq)'
# redeploy with new container
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - '$_SSH_STRING'
  - '--project'
  - '$PROJECT_ID'
  - '--zone'
  - '$_ZONE'
  - '--'
  - 'docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v $_HOME/.caddy:/root/.caddy gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'
